# version: '3.8'

# services:
#   web:
#     build: .
#     command: python manage.py runserver 0.0.0.0:8000
#     volumes:
#       - .:/code
#     ports:
#       - "8000:8000"
#     depends_on:
#       - db

#   db:
#     image: postgres:13
#     volumes:
#       - postgres_data:/var/lib/postgresql/data/
#     environment:
#       POSTGRES_DB: recallServer
#       POSTGRES_USER: comon
#       POSTGRES_PASSWORD: password

# volumes:
#   postgres_data:
version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: recallserver
      POSTGRES_USER: comon
      POSTGRES_PASSWORD: password
    volumes:
      - npgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  pgdata:

