databases:
  - name: recallserverdb
    plan: free
    databaseName: recallserver
    user: comon

services:
  - type: web
    plan: free
    name: recall_server
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn recall_server.config.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: recallserverdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
